name = Song
description = A song's layouts.
preview = preview.png
template = song-layout

; Regions
regions[navigation] = Navigation
regions[banner] = Banner
regions[search] = Search
regions[preface] = Preface
regions[featured] = Featured
regions[help] = Help
regions[content] = Content
regions[postscript] = Postscript
regions[sidebar_first] = Sidebar First
regions[sidebar_second] = Sidebar Second
regions[footer] = Footer
regions[footer_second] = Footer Second

; Stylesheets
stylesheets[all][] = css/layouts/song/song.layout.css
scripts[] = js/song.layout.js

